#ifndef COMMON_H_
#define COMMON_H_


#define AA_NUM 19
#define MAX_SEQ_LEN 100
#define DEFAULT_EXCHG_TIMES 20
#define DEFAULT_TIME_LIMIT 1
#define AAC_CAPACITY 10000
#define MASS_THRESHHOLD 1005.4433
#define AAC_TIME_SEED 10000
//#define AAC_DEBUG

#define AAS_NUM_PER_AAC 10 
#define SATISFY_THRESHHOLD 0.8

#endif /*COMMON_H_*/
